/-
Copyright (c) 2026 Shuoming An. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shuoming An
-/
import QECCertificates.Homology.ModuleExpansion
import QECCertificates.Homology.AuxComplex

open QECCertificates

/-!
# The port function $f_p$ and "$W$ generated by $f_p(\xi_i)$" (the hypothesis of Theorem 7.7)

The layer recorded as **not done** in item 4 of "Honest boundaries" in §4 of
`Homology/ModuleExpansion.lean`:

> **The layer "$W$ is generated by $f_p(\xi_i)$"**: this module takes the $\kappa$ family
> as a **parameter** (`κ : ι → Finset V`, where $\iota$ is $2^I$), and does not construct
> its relation to the port function.

This module supplies that layer: it makes the **port function** $f_p$ and its image
$V_i = f_p(\xi_i)$ from the statement of [14] Theorem 7.7 into machine-checkable objects,
and proves that the resulting $\kappa$ family (the indicator vectors of the $V_i$) indeed
satisfies the three consumption interfaces of `ModuleExpansion.lean` — the $\kappa$ parameter
of `HasModularExpansion`, the `hκU` hypothesis of `preservesDistance_of_thicken`, and the
$\ker(G^{\mathsf T}) \subseteq W$ hypothesis of Lemma 7.9.

**This module does only that layer**: the **distance-transfer body** of Theorem 7.7 (the
distance of the deformed code $Q \bowtie \mathcal H$ is $\ge d$) is not in this module, see
"Honest boundaries" in §4.

## 1. The source of [14] (the only source of this module's definitions)

[14] = Cowtan–He–Williamson–Yoder, *Fast and fault-tolerant logical measurements:
auxiliary hypergraphs and transversal surgery*, arXiv:2510.14895.

**Theorem 7.7** (p. 36–37, the target of this module):

> Let $\{Z_i\}_{i \in I}$ be a set of logical representatives (trivial or nontrivial) on a
> distance $d$ CSS code $Q$ with supports $\xi_i = \operatorname{supp}(Z_i)$. Let
> $\mathcal H(\mathcal V, \mathcal E)$ be a hypergraph with vertices in $\mathcal V$ being $Z$
> checks, hyperedges in $\mathcal E$ data qubits and $X$ gauge checks forming a cycle basis,
> such that $\mathcal H$ measures all the logical representatives $\{Z_i\}$. Let
> $f_p : \bigsqcup_i \xi_i \to \mathcal V$ be an injective port function such that
> $\mathcal U = \operatorname{im} f_p \subset \mathcal V$, and
> $f_p(\xi_i) = V_i \subset \mathcal V$, $\forall i \in I$. Let $\mathcal M_d(\mathcal H) \ge 1$,
> **where $W$ is generated by $f_p(\xi_i)$**. Then the distance of the deformed code
> $Q \bowtie \mathcal H$ is at least $d$.

Two layers in this sentence must be kept apart: $W$ **is generated by $f_p(\xi_i)$** (this is
the **definition** of $W$), while $\mathcal M_d \ge 1$ is the inequality of Def 7.2, whose
$\min$ is taken over $\kappa_\lambda \in W$. Definition 7.1 (p. 35) writes it as: the $v_i$
form a basis of $W$, $V_i = \operatorname{supp}(v_i)$ and $\mathcal U = \bigcup_i V_i$; the
$\min$ of Def 7.2 is taken over $\lambda \in 2^I$, that is, $\kappa_\lambda$ runs over those
elements of $W$ that are **built from several of the $V_i$**.

## 2. This module's encoding (the convention)

* **The port function**: $f_p : \bigsqcup_i \xi_i \to \mathcal V$ is written as
  `fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k` — the domain is the `Sigma` encoding
  of $\bigsqcup_i \xi_i$ (`PortDomain`) and the codomain $\mathcal V$ is `Fin k`. Its
  **injectivity** is written as the explicit hypothesis `IsPortFunction ξ fp`
  (`Function.Injective` on `PortDomain ξ`), **not hidden inside a structure** — so the
  hypothesis list of each theorem is self-contained and readable, and a downstream user can
  take just the one they need.
* **$V_i$ and $\mathcal U$**: `portImage ξ fp i = (ξ i).attach.image (fp i ·)` and
  `portUnion ξ fp = univ.biUnion (portImage ξ fp)` ($\mathcal U = \operatorname{im} f_p$).
* **The $\kappa$ family**: `kappa ξ fp i = indVec (portImage ξ fp i)` (the indicator vector
  of $V_i$; `indVec` reuses the existing definition of `Homology/AuxComplex.lean`), with
  `W ξ fp = spanL (List.ofFn (kappa ξ fp))`.
* **The $2^I$ index family**: `blockUnion V s = s.biUnion V` — the very family of the
  $\kappa_\lambda$ ($\lambda \in 2^I$) of Def 7.2, and the correct instantiation of
  `κ : Finset (Fin I) → Finset (Fin k)` in `ModuleExpansion.lean`.

## 3. The main results

* **`portImage_disjoint`**: injectivity of the port function ⟹ the $V_i$ for different $i$
  are **pairwise disjoint**. (**One point of convention**: this one does **not** use the
  extra hypothesis "the supports $\xi_i$ are pairwise disjoint" — the domain of $f_p$ is
  already $\bigsqcup_i \xi_i$, and injectivity sends the ports of different $i$ to different
  vertices, so $V_i \cap V_j = \varnothing$ is a **theorem** and not a hypothesis. This is
  **weaker** than "the $\xi$ are disjoint": $f_p$ may well send two copies of the same data
  qubit to two different vertices.)
* **`kappa_linearIndependent`**: $\{\kappa_i\}$ is linearly independent; with `finrank_W`
  this gives $\dim W = |I|$. **Two explicit hypotheses**: the $V_i$ are pairwise disjoint
  (supplied free by the theorem above) and **$V_i \ne \varnothing$** (that is, `ξ i` is
  nonempty). The latter is **not free**: $Z_i$ is a logical representative so its support is
  nonempty, but "the support is nonempty" comes from the code side (this library does not
  formalize the relation between $Z_i$ and the code), so it is taken as an explicit
  hypothesis. Without it `dim W = |I|` is **false** (an empty support gives $\kappa_i = 0$).
* **`mem_W_iff_blockUnion` (membership characterisation)**: $w \in W \iff$ $w$ is the
  indicator vector of a **union of some of the $V_i$**. This is the entire set-theoretic
  content of the sentence "$W$ is generated by $f_p(\xi_i)$".
* **`ker_subset_W_iff_blockUnion` / `ker_subset_W_iff_isComponent` (the hypothesis of
  Lemma 7.9)**: $\ker(G^{\mathsf T}) \subseteq W$ $\iff$ every element of
  $\ker(G^{\mathsf T})$ is a union of some of the $V_i$. The right-hand side is the
  word-for-word form of "each element in $\ker(G^{\mathsf T})$ has the supporting set
  $\kappa_\lambda$ for some $\lambda \in 2^I$" from [14] Lemma 7.9; after connecting it with
  the existing `edgeDeg_eq_zero_iff_isComponent`, the same sentence can be written in the
  component (`IsComponent`) form, so "the $W$ of the port data" and the component layer of
  `Homology/HypergraphSurgery.lean` and the complex layer of `Homology/AuxComplex.lean` speak
  of the same $\ker$.
* **`preservesDistance_of_portData` (the bridge to the consumer)**: it assembles the two
  hypotheses of `ModuleExpansion.preservesDistance_of_thicken` (`hκU` and `hker`) on port
  data — `hκU` is supplied by `blockUnion_subset_portUnion`, and the assumed form of `hker`
  is the union form of $\ker \subseteq W$ above. Thus the passage "the hypothesis is
  constructively satisfiable" of Thm 7.7 / Cor 7.10 **no longer needs the caller to
  hand-assemble the $\kappa$ family**.

## 4. Honest boundaries

**Done**: the encoding of the port function and its injectivity corollaries ($V_i$ pairwise
disjoint, $V_i$ equinumerous with $\xi_i$, $\mathcal U = \bigcup_i V_i$), the definition and
linear independence of the $\kappa$ family, $\dim W = |I|$, the membership characterisation
of $W$ (both the coefficient form and the union form), the form of the hypothesis of
Lemma 7.9 and its connection to the existing component layer, and the bridge to
`preservesDistance_of_thicken`.

**Not done, and not claimed** (item by item):

1. **The distance-transfer body of Theorem 7.7**. The "distance of the deformed code
   $Q \bowtie \mathcal H$ is $\ge d$" in the statement needs the **gluing assembly of the
   deformed code** of [14] (the mapping cone, the joining of $Q$ and $\mathcal H$, and the
   condition on the side "$\mathcal H$ measures all the logical representatives"). This
   library does **not** formalize the deformed code, so this theorem **cannot be stated** in
   this library, and this module does not touch it at all. What this module delivers is
   **one layer** of its hypotheses (the source of $W$), not the theorem itself.
2. **The seven-region Venn count of Appendix C: not in this module, already machine-checked
   by `the gauged-measurement companion development's `VennPartition` module`**. (**The determinacy of the partition**: enumerate
   cell by cell according to the set memberships, then **solve back** for the region
   membership — the partition splits $\kappa_\lambda\setminus v$ and
   $(v\cap\mathcal U)\setminus\kappa_\lambda$ each in two according to membership in
   $\bar\Lambda_Z$, and equation (2) is an **identity** under that partition.)
   Still **not done** are equations (1) and (3) — they are operator-level products and
   supports, and need the deformed-code $Q\leftrightarrow H$ semantics.
3. **The layer "$Z_i$ is a logical representative of a distance $d$ CSS code $Q$"**. This
   module takes $\xi_i$ as a parameter and **does not construct** its relation to a concrete
   code: it neither proves "$Z_i$ is a logical-operator representative", nor
   "$|\xi_i| \ge d$", nor handles the "trivial or nontrivial" distinction. (This is exactly
   why $V_i \ne \varnothing$ in §3 can only be an explicit hypothesis.)
4. **The three conditions on the $\mathcal H$ side**: "$\mathcal V$ is the $Z$ checks",
   "$\mathcal E$ is the data qubits and the $X$ gauge checks that form a cycle basis", and
   "$\mathcal H$ measures all the logical representatives". The codomain of the port
   function in this module is just an abstract `Fin k` and is **not tied to any concrete
   `AuxHypergraph`**; whether $k$ agrees with the vertex set of the hypergraph, and whether
   $\mathcal U \subset \mathcal V$ is a strict inclusion, are not in this module.
5. **The choice of the $v_i$ (the basis vectors of $W$) itself**. Def 7.1 says the $v_i$ are
   a basis of $W$ and $V_i = \operatorname{supp}(v_i)$, i.e. $\kappa_\lambda = \sum_{i \in
   \lambda} v_i$. This module goes the **other way**: first the $V_i$ (the port images),
   then $\kappa_i$ as their indicator vectors, so that the support of
   $\kappa_\lambda = \sum_{i \in \lambda} \kappa_i$ is exactly $\bigcup_{i \in \lambda} V_i$.
   On this family the two write-ups are the same thing (`coeffVec_indicator_eq_indVec` and
   `mem_W_iff_blockUnion` do the step "the sum is the indicator vector of the union"), but
   the stronger assertion "the $v_i$ are a **basis**" (each $v_i$ is an element of $W$, with
   pairwise distinct supports) is not stated separately in this module — it is implied by
   `kappa_linearIndependent` + `mem_W_iff_blockUnion` taken together, and this is noted
   honestly here: it is **not** written as a separate theorem "this family is a basis".
6. **The "numerical" relation of §5 to `hasModularExpansion`**. This module proves only that
   the **formal hypotheses** on the $\kappa$ family (the membership characterisation, the
   dimension, `hκU`) hold; it does **not** compute the value of $\mathcal M_t$, and it does
   not prove "the $\mathcal M_t$ obtained from this $\kappa$ family agrees with the one
   obtained from another family".

**Trust base**: this module uses no `sorry` / `admit` / `native_decide` and introduces no
custom axioms; the `#print axioms` of the load-bearing theorems is wired in centrally by the
root module `QECCertificates.lean`.
-/

namespace QECCertificates.Homology

open scoped BigOperators

/-! ## 1. The port function and its image -/

/-- The `Sigma` encoding of $\bigsqcup_i \xi_i$: the **domain** of the port function $f_p$.
`p.1` is the representative index $i$ and `p.2` is the data qubit lying in $\xi_i$ (with a
membership proof). -/
abbrev PortDomain {n I : ℕ} (ξ : Fin I → Finset (Fin n)) :=
  Sigma (fun i : Fin I => {v : Fin n // v ∈ ξ i})

/-- The **injectivity** of the **port function** $f_p : \bigsqcup_i \xi_i \to \mathcal V$.
The machine form of the "injective port function" of [14] Thm 7.7: the domain is written as
the `Sigma` encoding `PortDomain ξ` of $\bigsqcup_i \xi_i$ (`i` is the representative and `v`
is the data qubit), so "injective" means injective on the **whole** of $\bigsqcup$ — ports of
different `i` do not collide, and neither do ports within one `i`.

Following the convention of the task specification, injectivity is written as an **explicit
hypothesis** rather than a structure field: each theorem declares whether it needs it. -/
def IsPortFunction {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) : Prop :=
  Function.Injective (fun p : PortDomain ξ => fp p.1 p.2)

/-- $V_i = f_p(\xi_i)$: the **image** of the support of the `i`th logical representative
under the port function. -/
def portImage {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) (i : Fin I) : Finset (Fin k) :=
  (ξ i).attach.image (fun v => fp i v)

/-- $\mathcal U = \operatorname{im} f_p = \bigcup_i V_i$. -/
def portUnion {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) : Finset (Fin k) :=
  Finset.univ.biUnion (portImage ξ fp)

/-- The union $\bigcup_{i \in s} V_i$ corresponding to a subfamily `s ⊆ I` (the domain is an
arbitrary family `V`; in §5 it is used with `V := portImage ξ fp`). -/
def blockUnion {k I : ℕ} (V : Fin I → Finset (Fin k)) (s : Finset (Fin I)) : Finset (Fin k) :=
  s.biUnion V

@[simp] theorem mem_portImage {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} {i : Fin I} {x : Fin k} :
    x ∈ portImage ξ fp i ↔ ∃ v : {v : Fin n // v ∈ ξ i}, fp i v = x := by
  rw [portImage, Finset.mem_image]
  exact ⟨fun ⟨v, _, hv⟩ => ⟨v, hv⟩, fun ⟨v, hv⟩ => ⟨v, Finset.mem_attach _ v, hv⟩⟩

@[simp] theorem mem_portUnion {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} {x : Fin k} :
    x ∈ portUnion ξ fp ↔ ∃ i : Fin I, x ∈ portImage ξ fp i := by
  rw [portUnion, Finset.mem_biUnion]
  exact ⟨fun ⟨i, _, h⟩ => ⟨i, h⟩, fun ⟨i, h⟩ => ⟨i, Finset.mem_univ i, h⟩⟩

/-- **Injectivity of the port function ⟹ the $V_i$ for different $i$ are disjoint**
(pointwise form).

Note that this does **not** use "the $\xi_i$ are pairwise disjoint": the domain is
$\bigsqcup_i \xi_i$, and injectivity by itself sends the ports of different $i$ to different
vertices. See the convention note in §3 of the module docstring. -/
theorem portImage_notMem_of_ne {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    {i j : Fin I} (hij : i ≠ j) {x : Fin k} (hx : x ∈ portImage ξ fp i) :
    x ∉ portImage ξ fp j := by
  intro hxj
  rw [mem_portImage] at hx hxj
  obtain ⟨v, hv⟩ := hx
  obtain ⟨w, hw⟩ := hxj
  have hcongr : (⟨i, v⟩ : PortDomain ξ) = ⟨j, w⟩ :=
    hπ (by change fp i v = fp j w; rw [hv, hw])
  exact hij (congrArg Sigma.fst hcongr)

/-- **Injectivity of the port function ⟹ the $V_i$ are pairwise disjoint** (the `Finset`
`Disjoint` form). -/
theorem portImage_disjoint {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    {i j : Fin I} (hij : i ≠ j) : Disjoint (portImage ξ fp i) (portImage ξ fp j) := by
  rw [Finset.disjoint_left]
  intro x hx hxj
  exact portImage_notMem_of_ne hπ hij hx hxj

/-- Injectivity also holds **within one `i`** (`f_p` restricted to a single $\xi_i$ is
injective). -/
theorem portImage_fiber_injective {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    {i : Fin I} {v w : {v : Fin n // v ∈ ξ i}} (h : fp i v = fp i w) : v = w := by
  have hcongr : (⟨i, v⟩ : PortDomain ξ) = ⟨i, w⟩ := hπ h
  have h3 : (v : Fin n) = (w : Fin n) :=
    congrArg Prod.fst (congrArg (fun p : PortDomain ξ => ((p.2 : Fin n), p.1)) hcongr)
  exact Subtype.ext h3

/-- $|V_i| = |\xi_i|$: the port function is a bijection on each support (injective + image). -/
theorem portImage_card {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    (i : Fin I) : (portImage ξ fp i).card = (ξ i).card := by
  rw [portImage, Finset.card_image_of_injective _ (fun v w h => portImage_fiber_injective hπ h),
    Finset.card_attach]

/-- $V_i \ne \varnothing$ ⟸ $\xi_i \ne \varnothing$ (the image of the port function is nonempty). -/
theorem portImage_nonempty {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} {i : Fin I}
    (h : (ξ i).Nonempty) : (portImage ξ fp i).Nonempty := by
  obtain ⟨v, hv⟩ := h
  exact ⟨fp i ⟨v, hv⟩, (mem_portImage).mpr ⟨⟨v, hv⟩, rfl⟩⟩

/-- $V_i \subseteq \mathcal U$ ($\mathcal U$ is the union of all the $V_i$). -/
theorem portImage_subset_portUnion {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) (i : Fin I) :
    portImage ξ fp i ⊆ portUnion ξ fp :=
  Finset.subset_biUnion_of_mem _ (Finset.mem_univ i)

/-- **The union of an arbitrary subfamily still lies in $\mathcal U$**: this is the `hκU`
hypothesis of `ModuleExpansion.preservesDistance_of_thicken`
($\forall a,\ \kappa_a \subseteq \mathcal U$) instantiated on port data. -/
theorem blockUnion_subset_portUnion {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) (s : Finset (Fin I)) :
    blockUnion (portImage ξ fp) s ⊆ portUnion ξ fp :=
  Finset.biUnion_subset_biUnion_of_subset_left _ (Finset.subset_univ s)

/-! ## 2. The $\kappa$ family and $W$ -/

/-- $\kappa_i$: the **indicator vector** of $V_i = f_p(\xi_i)$ in $\mathbb F_2^{\mathcal V}$.
(`indVec` reuses the definition of `Homology/AuxComplex.lean`.) -/
def kappa {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) (i : Fin I) : Vec k :=
  indVec (portImage ξ fp i)

/-- The **abstract** form of $W$: the subspace spanned by the indicator vectors of an
arbitrary family `V` (in §5 it is instantiated with `V := portImage ξ fp` to give the $W$ of
Theorem 7.7). -/
def kappaSpan {k I : ℕ} (V : Fin I → Finset (Fin k)) : Submodule (ZMod 2) (Vec k) :=
  spanL (List.ofFn fun i => indVec (V i))

/-- **$W = \operatorname{span}\{\kappa_i\}$** — the machine form of "where $W$ is generated
by $f_p(\xi_i)$" in Theorem 7.7. -/
def W {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) : Submodule (ZMod 2) (Vec k) :=
  kappaSpan (portImage ξ fp)

/-- $W$ is the subspace spanned by $\{\kappa_i\}$ (definitional, by `rfl`). -/
theorem W_eq_spanL_kappa {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) :
    W ξ fp = spanL (List.ofFn (kappa ξ fp)) := rfl

/-! ### Small lemmas on indicator vectors

(Placed here rather than in §3: `kappa_apply` / `kappa_ne_zero` need them.) -/

theorem indVec_apply {k : ℕ} (S : Finset (Fin k)) (x : Fin k) :
    indVec S x = if x ∈ S then 1 else 0 := rfl

theorem indVec_apply_eq_one {k : ℕ} {S : Finset (Fin k)} {x : Fin k} (hx : x ∈ S) :
    indVec S x = 1 := by
  rw [indVec_apply, ite_eq_left hx]

theorem indVec_apply_eq_zero {k : ℕ} {S : Finset (Fin k)} {x : Fin k} (hx : x ∉ S) :
    indVec S x = 0 := by
  rw [indVec_apply, ite_eq_right hx]

theorem indVec_apply_ne_zero_iff {k : ℕ} (S : Finset (Fin k)) (x : Fin k) :
    indVec S x ≠ 0 ↔ x ∈ S := by
  rw [indVec_apply]
  by_cases h : x ∈ S
  · rw [ite_eq_left h]
    exact ⟨fun _ => h, fun _ => one_ne_zero⟩
  · rw [ite_eq_right h]
    exact ⟨fun h0 => absurd rfl h0, fun hc => absurd hc h⟩

/-- The indicator vector is **injective**: the set can be read back off the vector. -/
theorem indVec_injective {k : ℕ} : Function.Injective (indVec : Finset (Fin k) → Vec k) := by
  intro S T h
  ext x
  rw [← indVec_apply_ne_zero_iff S x, ← indVec_apply_ne_zero_iff T x, h]

theorem indVec_ne_zero_of_nonempty {k : ℕ} {S : Finset (Fin k)} (h : S.Nonempty) :
    indVec S ≠ 0 := by
  obtain ⟨x, hx⟩ := h
  intro hzero
  have := congrFun hzero x
  rw [Pi.zero_apply, indVec_apply_eq_one hx] at this
  exact one_ne_zero this

theorem indVec_add_of_disjoint {k : ℕ} {A B : Finset (Fin k)} (h : Disjoint A B) :
    indVec A + indVec B = indVec (A ∪ B) := by
  funext x
  rw [Pi.add_apply, indVec_apply, indVec_apply, indVec_apply]
  by_cases hA : x ∈ A
  · have hB : x ∉ B := fun hB => (Finset.disjoint_left.mp h hA) hB
    rw [ite_eq_left hA, ite_eq_right hB,
      ite_eq_left (Finset.mem_union.mpr (Or.inl hA)), add_zero]
  · by_cases hB : x ∈ B
    · rw [ite_eq_right hA, ite_eq_left hB,
        ite_eq_left (Finset.mem_union.mpr (Or.inr hB)), zero_add]
    · rw [ite_eq_right hA, ite_eq_right hB,
        ite_eq_right (fun hc => (Finset.mem_union.mp hc).elim hA hB), add_zero]

/-! ### The pointwise value and nonvanishing of $\kappa$ -/

theorem kappa_apply {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) (i : Fin I) (x : Fin k) :
    kappa ξ fp i x = if x ∈ portImage ξ fp i then 1 else 0 :=
  indVec_apply (portImage ξ fp i) x

theorem kappa_ne_zero {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} {i : Fin I}
    (h : (ξ i).Nonempty) : kappa ξ fp i ≠ 0 :=
  indVec_ne_zero_of_nonempty (portImage_nonempty h)

/-! ## 3. The membership characterisation of $W$

Two levels of characterisation:
* **coefficient form** (`mem_kappaSpan_iff_coeff`): $w \in W$ $\iff$ $w = \sum_i c_i
  \kappa_i$ — expanding $\kappa_i$ directly into a coordinatewise partial sum;
* **union form** (`mem_kappaSpan_iff_blockUnion`, the main theorem of this section):
  $w \in W$ $\iff$ $w$ is the indicator vector of a **union of some of the $V_i$** — this is
  the set-theoretic content of "$W$ is generated by $f_p(\xi_i)$".

The hinge between the two steps is a **collapse lemma**: when the $V_i$ are pairwise
disjoint, at most one term of $\sum_i f_i \cdot [x \in V_i]$ is nonzero. -/

/-- **The collapse lemma (hit case)**: when $x \in V_{i_0}$ and the $V$ are pairwise
disjoint, $\sum_i f_i \cdot [x \in V_i] = f_{i_0}$. -/
theorem sum_mul_indVec_apply_of_mem {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (hdisj : ∀ i j : Fin I, i ≠ j → Disjoint (V i) (V j)) (f : Fin I → ZMod 2)
    {i₀ : Fin I} {x : Fin k} (hx : x ∈ V i₀) :
    (∑ i, f i * (if x ∈ V i then 1 else 0)) = f i₀ := by
  rw [Finset.sum_eq_single (s := Finset.univ)
    (f := fun i => f i * (if x ∈ V i then 1 else 0)) i₀
    (fun b _ hb => by
      have hxb : x ∉ V b := fun hxb => (Finset.disjoint_left.mp (hdisj b i₀ hb) hxb) hx
      rw [ite_eq_right hxb, mul_zero])
    (fun hnot => absurd (Finset.mem_univ i₀) hnot)]
  rw [ite_eq_left hx, mul_one]

/-- **The collapse lemma (vanishing case)**: if $f_i = 0$ on every $V_i$ containing $x$,
then the whole sum is zero. (The disjoint case's "$x$ lies in no $V_i$" is a special case:
the hypothesis is vacuously true.) -/
theorem sum_mul_indVec_apply_eq_zero {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (f : Fin I → ZMod 2) {x : Fin k} (h : ∀ i, x ∈ V i → f i = 0) :
    (∑ i, f i * (if x ∈ V i then 1 else 0)) = 0 := by
  rw [Finset.sum_eq_zero]
  intro i _
  by_cases hxi : x ∈ V i
  · rw [ite_eq_left hxi, mul_one, h i hxi]
  · rw [ite_eq_right hxi, mul_zero]

/-- The coordinatewise form of the coefficient vector:
$\bigl(\sum_i c_i \kappa_i\bigr)_x = \sum_i c_i [x \in V_i]$. -/
def coeffVec {k I : ℕ} (V : Fin I → Finset (Fin k)) (c : Fin I → ZMod 2) : Vec k :=
  fun x => ∑ i, c i * (if x ∈ V i then 1 else 0)

theorem coeffVec_apply {k I : ℕ} (V : Fin I → Finset (Fin k)) (c : Fin I → ZMod 2)
    (x : Fin k) : coeffVec V c x = ∑ i, c i * (if x ∈ V i then 1 else 0) := rfl

/-- `coeffVec` is exactly $\sum_i c_i \kappa_i$. -/
theorem coeffVec_eq_sum_smul {k I : ℕ} (V : Fin I → Finset (Fin k)) (c : Fin I → ZMod 2) :
    coeffVec V c = ∑ i, c i • indVec (V i) := by
  funext x
  rw [Finset.sum_apply, coeffVec_apply]
  exact Finset.sum_congr rfl (fun i _ => by rw [Pi.smul_apply, smul_eq_mul, indVec_apply])

/-- `coeffVec` lies in $W$ (it is a linear combination of the $\kappa_i$). -/
theorem coeffVec_mem {k I : ℕ} (V : Fin I → Finset (Fin k)) (c : Fin I → ZMod 2) :
    coeffVec V c ∈ kappaSpan V := by
  rw [coeffVec_eq_sum_smul]
  refine Submodule.sum_mem _ (fun i _ => ?_)
  exact Submodule.smul_mem _ (c i) (subset_spanL (List.mem_ofFn.mpr ⟨i, rfl⟩))

/-- **The coefficient form of the membership characterisation**: $w \in W$ $\iff$
$w = \sum_i c_i \kappa_i$ (written as a coordinatewise partial sum). -/
theorem mem_kappaSpan_iff_coeff {k I : ℕ} (V : Fin I → Finset (Fin k)) (w : Vec k) :
    w ∈ kappaSpan V ↔ ∃ c : Fin I → ZMod 2, w = coeffVec V c := by
  constructor
  · intro hw
    refine Submodule.span_induction (p := fun w _ => ∃ c : Fin I → ZMod 2, w = coeffVec V c)
      ?_ ?_ ?_ ?_ hw
    · intro x hx
      have hx' : x ∈ List.ofFn (fun i : Fin I => indVec (V i)) := hx
      rw [List.mem_ofFn] at hx'
      obtain ⟨i, rfl⟩ := hx'
      refine ⟨fun j => if j = i then 1 else 0, ?_⟩
      funext x'
      rw [indVec_apply, coeffVec_apply]
      rw [Finset.sum_eq_single (s := Finset.univ)
        (f := fun j => (if j = i then (1 : ZMod 2) else 0) * (if x' ∈ V j then 1 else 0)) i
        (fun b _ hb => by rw [ite_eq_right hb, zero_mul])
        (fun hnot => absurd (Finset.mem_univ i) hnot)]
      rw [ite_eq_left rfl, one_mul]
    · refine ⟨fun _ => 0, ?_⟩
      funext x
      rw [Pi.zero_apply, coeffVec_apply]
      exact (Finset.sum_eq_zero (fun i _ => by simp)).symm
    · rintro x y _ _ ⟨c₁, h₁⟩ ⟨c₂, h₂⟩
      refine ⟨c₁ + c₂, ?_⟩
      rw [h₁, h₂]
      funext x
      rw [Pi.add_apply, coeffVec_apply, coeffVec_apply, coeffVec_apply,
        ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl (fun i _ => (add_mul (c₁ i) (c₂ i) _).symm)
    · rintro a x _ ⟨c, h⟩
      refine ⟨fun i => a * c i, ?_⟩
      rw [h]
      funext x
      rw [Pi.smul_apply, smul_eq_mul, coeffVec_apply, coeffVec_apply, Finset.mul_sum]
      exact Finset.sum_congr rfl (fun i _ => (mul_assoc a (c i) _).symm)
  · rintro ⟨c, rfl⟩
    exact coeffVec_mem V c

/-- **Indicator family ⟹ the indicator vector of the union**: $\sum_i [i \in s] \cdot
[x \in V_i] = [x \in \bigcup_{i\in s} V_i]$ — that is, $\sum_{i \in s} \kappa_i$ is exactly
the indicator vector of $\bigcup_{i \in s} V_i$. -/
theorem coeffVec_indicator_eq_indVec {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (hdisj : ∀ i j : Fin I, i ≠ j → Disjoint (V i) (V j)) (s : Finset (Fin I)) :
    coeffVec V (fun i => if i ∈ s then 1 else 0) = indVec (s.biUnion V) := by
  funext x
  by_cases hx : x ∈ s.biUnion V
  · obtain ⟨i, his, hxi⟩ := Finset.mem_biUnion.mp hx
    rw [coeffVec_apply, sum_mul_indVec_apply_of_mem hdisj (fun j => if j ∈ s then 1 else 0) hxi,
      ite_eq_left his]
    exact (indVec_apply_eq_one hx).symm
  · rw [coeffVec_apply, sum_mul_indVec_apply_eq_zero (fun j => if j ∈ s then 1 else 0)
      (fun j hxj => ite_eq_right (fun hjs => hx (Finset.mem_biUnion.mpr ⟨j, hjs, hxj⟩)))]
    exact (indVec_apply_eq_zero hx).symm

/-- **The union form of the membership characterisation (the main theorem of this section)**:
$w \in W$ $\iff$ $w$ is the indicator vector of a **union of some of the $V_i$**. This is
the set-theoretic content of "where $W$ is generated by $f_p(\xi_i)$" in [14] Thm 7.7. -/
theorem mem_kappaSpan_iff_blockUnion {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (hdisj : ∀ i j : Fin I, i ≠ j → Disjoint (V i) (V j)) (w : Vec k) :
    w ∈ kappaSpan V ↔ ∃ s : Finset (Fin I), w = indVec (s.biUnion V) := by
  rw [mem_kappaSpan_iff_coeff]
  constructor
  · rintro ⟨c, rfl⟩
    refine ⟨Finset.univ.filter (fun i => c i ≠ 0), ?_⟩
    funext x
    by_cases hx : x ∈ (Finset.univ.filter (fun i => c i ≠ 0)).biUnion V
    · obtain ⟨i, hi, hxi⟩ := Finset.mem_biUnion.mp hx
      rw [coeffVec_apply, sum_mul_indVec_apply_of_mem hdisj c hxi, indVec_apply_eq_one hx]
      exact eq_one_of_ne_zero (Finset.mem_filter.mp hi).2
    · have hz : (∑ i, c i * (if x ∈ V i then 1 else 0)) = 0 :=
        sum_mul_indVec_apply_eq_zero c (fun i hxi => by
          by_contra hne
          exact hx (Finset.mem_biUnion.mpr
            ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hne⟩, hxi⟩))
      rw [coeffVec_apply, hz, indVec_apply_eq_zero hx]
  · rintro ⟨s, rfl⟩
    exact ⟨fun i => if i ∈ s then 1 else 0, (coeffVec_indicator_eq_indVec hdisj s).symm⟩

/-- **The membership characterisation on port data**: $w \in W \iff w$ is the indicator
vector of a union of some $V_i = f_p(\xi_i)$. -/
theorem mem_W_iff_blockUnion {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    (w : Vec k) :
    w ∈ W ξ fp ↔ ∃ s : Finset (Fin I), w = indVec (blockUnion (portImage ξ fp) s) :=
  mem_kappaSpan_iff_blockUnion (fun _i _j hij => portImage_disjoint hπ hij) w

theorem mem_W_iff_coeff {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (w : Vec k) :
    w ∈ W ξ fp ↔ ∃ c : Fin I → ZMod 2, w = coeffVec (portImage ξ fp) c :=
  mem_kappaSpan_iff_coeff (portImage ξ fp) w

/-! ## 4. Linear independence of $\{\kappa_i\}$ and $\dim W = |I|$ -/

/-- **$\{\kappa_i\}$ is linearly independent**: when the $V_i$ are pairwise disjoint and
**nonempty**, $\sum_i c_i \kappa_i = 0$ read at any point of $V_{i_0}$ gives $c_{i_0} = 0$.

Nonemptiness is not free (an empty $V_i$ gives $\kappa_i = 0$; see `kappa_ne_zero` and §3
of the module docstring). -/
theorem kappa_linearIndependent {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (hdisj : ∀ i j : Fin I, i ≠ j → Disjoint (V i) (V j))
    (hne : ∀ i, (V i).Nonempty) :
    LinearIndependent (ZMod 2) (fun i => indVec (V i)) := by
  rw [Fintype.linearIndependent_iff]
  intro g hsum i
  obtain ⟨x, hx⟩ := hne i
  have hval := congrFun hsum x
  rw [Finset.sum_apply, Pi.zero_apply] at hval
  have h' : (∑ j, g j * (if x ∈ V j then 1 else 0)) = 0 :=
    (Finset.sum_congr rfl
      (fun j _ => by rw [Pi.smul_apply, smul_eq_mul, indVec_apply])).trans hval
  rw [sum_mul_indVec_apply_of_mem hdisj g hx] at h'
  exact h'

/-- **$\dim W = |I|$**: from `kappa_linearIndependent` and `finrank_span_eq_card`. -/
theorem finrank_kappaSpan {k I : ℕ} {V : Fin I → Finset (Fin k)}
    (hdisj : ∀ i j : Fin I, i ≠ j → Disjoint (V i) (V j))
    (hne : ∀ i, (V i).Nonempty) :
    Module.finrank (ZMod 2) (kappaSpan V) = I := by
  have hspan : kappaSpan V =
      Submodule.span (ZMod 2) (Set.range (fun i : Fin I => indVec (V i))) :=
    spanL_ofFn_eq_span_range (f := fun i : Fin I => indVec (V i))
  rw [hspan,
    finrank_span_eq_card (R := ZMod 2) (b := fun i : Fin I => indVec (V i))
      (kappa_linearIndependent hdisj hne),
    Fintype.card_fin]

/-- **$\dim W = |I|$ on port data**: the $\xi_i$ must be nonempty (see §3 of the module
docstring). -/
theorem finrank_W {n k I : ℕ} {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp)
    (hξ : ∀ i, (ξ i).Nonempty) :
    Module.finrank (ZMod 2) (W ξ fp) = I :=
  finrank_kappaSpan (fun _i _j hij => portImage_disjoint hπ hij)
    (fun i => portImage_nonempty (hξ i))

/-! ## 5. The hypothesis of Lemma 7.9: $\ker(G^{\mathsf T}) \subseteq W$

The hypothesis of [14] Lemma 7.9 reads

> Let $\mathcal H(\mathcal V, \mathcal E)$ be a hypergraph such that each element in
> $\ker(G^{\mathsf T})$ has the supporting set $\kappa_\lambda$ for some $\lambda \in 2^I$.

The theorems of this section realise the two sides of that sentence separately: the **left**
is "every element of $\ker(G^{\mathsf T})$ (as an indicator vector) lies in $W$", and the
**right** is "every kernel element is a union of some $V_i$"; the two are exchanged word for
word by the main theorem of §3. A component-language version is also given for the existing
`edgeDeg` / `IsComponent` layer (`edgeDeg_eq_zero_iff_isComponent` of
`Homology/ModuleExpansion.lean`). -/

/-- **The port form of the hypothesis of Lemma 7.9**: $\ker(G^{\mathsf T}) \subseteq W$
$\iff$ every element of $\ker(G^{\mathsf T})$ is a union of some $V_i$.

(This library encodes a "kernel element" as its indicator vector: whether
$S \in \ker(G^{\mathsf T})$ is decided by `edgeDeg H S = 0`, and "$S$ lies in $W$" reads as
`indVec S ∈ W`.) -/
theorem ker_subset_W_iff_blockUnion {n k m I : ℕ} (H : AuxHypergraph k m)
    {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp) :
    (∀ S : Finset (Fin k), edgeDeg H S = 0 → indVec S ∈ W ξ fp) ↔
      (∀ S : Finset (Fin k), edgeDeg H S = 0 →
        ∃ s : Finset (Fin I), blockUnion (portImage ξ fp) s = S) := by
  constructor
  · intro h S hS
    obtain ⟨s, hs⟩ := (mem_W_iff_blockUnion hπ (indVec S)).mp (h S hS)
    exact ⟨s, (indVec_injective hs).symm⟩
  · intro h S hS
    obtain ⟨s, hs⟩ := h S hS
    exact (mem_W_iff_blockUnion hπ (indVec S)).mpr
      ⟨s, (congrArg indVec hs).symm⟩

/-- **The component form of the hypothesis of Lemma 7.9**: the same statement as
`ker_subset_W_iff_blockUnion`, but the kernel elements are expressed with the existing
`IsComponent` (the component predicate of [14] §1.2). -/
theorem ker_subset_W_iff_isComponent {n k m I : ℕ} (H : AuxHypergraph k m)
    {ξ : Fin I → Finset (Fin n)}
    {fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k} (hπ : IsPortFunction ξ fp) :
    (∀ S : Finset (Fin k), IsComponent H S → indVec S ∈ W ξ fp) ↔
      (∀ S : Finset (Fin k), IsComponent H S →
        ∃ s : Finset (Fin I), blockUnion (portImage ξ fp) s = S) := by
  constructor
  · intro h S hS
    exact (ker_subset_W_iff_blockUnion H hπ).mp
      (fun T hT => h T ((edgeDeg_eq_zero_iff_isComponent H T).mp hT)) S
      ((edgeDeg_eq_zero_iff_isComponent H S).mpr hS)
  · intro h S hS
    exact (ker_subset_W_iff_blockUnion H hπ).mpr
      (fun T hT => h T ((edgeDeg_eq_zero_iff_isComponent H T).mp hT)) S
      ((edgeDeg_eq_zero_iff_isComponent H S).mpr hS)

/-! ## 6. The bridge to the consumer (`ModuleExpansion.preservesDistance_of_thicken`)

The `preservesDistance_of_thicken` of `Homology/ModuleExpansion.lean` turns the
"constructively satisfiable hypothesis" of [14] Cor 7.10 into a theorem, and its `κ`
parameter is **abstract**; this section gives its instantiation on port data:
$\kappa := \bigl(s \mapsto \bigcup_{i \in s} V_i\bigr)$ (index set $2^I$, lined up word for
word with the $\lambda \in 2^I$ of Def 7.2) and $\mathcal U := \bigcup_i V_i$, with `hκU`
supplied by `blockUnion_subset_portUnion` and the assumed form of `hker` being the
right-hand side of `ker_subset_W_iff_blockUnion`. -/

/-- **Port data satisfies `hκU`**: $\forall s \in 2^I,\ \bigcup_{i \in s} V_i \subseteq
\mathcal U$, so this hypothesis of `preservesDistance_of_thicken` needs no manual check by
the caller. -/
theorem portData_hkappaU {n k I : ℕ} (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) :
    ∀ s : Finset (Fin I), blockUnion (portImage ξ fp) s ⊆ portUnion ξ fp :=
  blockUnion_subset_portUnion ξ fp

/-- **The port version of Cor 7.10**: instantiate the `κ` parameter of
`preservesDistance_of_thicken` as the $2^I$-indexed union family and `U` as
$\mathcal U = \operatorname{im} f_p$, so that the caller only has to give the **union form**
of "$\ker \subseteq W$" (the right-hand side of `ker_subset_W_iff_blockUnion`); the `hκU` in
the hypothesis list is discharged by `portData_hkappaU`. -/
theorem preservesDistance_of_portData {n k m I : ℕ} (H : AuxHypergraph k m)
    (ξ : Fin I → Finset (Fin n))
    (fp : (i : Fin I) → {v : Fin n // v ∈ ξ i} → Fin k) {d : ℕ} (hd : 1 ≤ d)
    (hker : ∀ S : Finset (Fin k), edgeDeg H S = 0 →
      ∃ s : Finset (Fin I), blockUnion (portImage ξ fp) s = S)
    (L : ℕ) (hL : d ≤ L) (l : Fin L) :
    PreservesDistance (thickenInc H L) (levelFam (blockUnion (portImage ξ fp)) l)
      (levelSet (portUnion ξ fp) l) d :=
  preservesDistance_of_thicken H (blockUnion (portImage ξ fp)) (portUnion ξ fp)
    (portData_hkappaU ξ fp) hd hker L hL l

end QECCertificates.Homology
